### PR TITLE
Created a script to get the server-check.sh as well as deleting the old one in the process also added a check for root on the main server-check script

### PR DESCRIPTION
**Pull request by BeanJr**
This took 2 commits because the sed command had to be typed a specific way

### CODE REVIEW

**Comment by zonzorp** [comment]
Your script is a good first try.
It tells me you are going to like the scripting course next semester.
I am a little unsure about the purpose of the script though. It seems to me you are going to have to manually do the same things to get and run your script as you would have to do just to get and run the server-check script. It feels redundant.

**Comment by BeanJr** [comment]
I realize this script may seem redundant (it probably is) but I just wanted to contribute something to make it easier for one to update their server check (once they get this they can run it without typing anything) the whole idea is to automate the process of your tutorial by using wget and sed (sed is probably not required for this particular script to run). Keep in mind that I started and finished this entire script in the new file page on my git repo (you probably used Xcode or some other coding application instead therefore requiring the sed command)

As much as I'd like to make this script a lot more useful, I can't due to my bash knowledge. Perhaps down the road this script can ask if the user wants to run the server check or not and call the script to run if yes is the case.

**Comment by BeanJr** [comment]
I've added a few more commits to the server-check file. Have a look

**Comment by zonzorp** [comment]
I added your idea of checking for root to the server-check script. I didn't put that into the script because I figure anyone who would use this script should definitely already know about the requirement for root permission. But having the check doesn't hurt, so I put it in.
I remain unconvinced that there is value in downloading and running a script to download and run a script.

**Comment by BeanJr** [comment]
Alright I suppose we'll leave it at the root check for server-check then

**Comment by zonzorp** [comment]
There are plenty of other ways the script could be improved, but it is a case of diminish return on effort. Too many other things to work on. I do thank you for your suggestions.

**Pull request closed without merging**
